services:
  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network

  api-gateway:
     image: api-gateway
     ports:
      - "8900:8900"
     depends_on:
      - eureka-server
     networks:
      - ecommerce-network

  product-catalog:
    image: product-catalog-service
    expose:
      - "8810"
    depends_on:
      - database
    networks:
      - ecommerce-network

  order-service:
    build: order-service
    expose:
      - "8813"
    depends_on:
      - database
    networks:
      - ecommerce-network

  user-service:
    build: user-service
    expose:
      - "8811"
    depends_on:
      - database
    networks:
      - ecommerce-network

  recommendation-service:
    build: product-recommendation-service
    ports:
      - "8812"
    depends_on:
      - database
    networks:
      - ecommerce-network

  database:
    image: mcr.microsoft.com/mssql/server:2019-latest  # SQL Server 2016 image
    environment:
      SA_password: "Password@1"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks: 
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge


